version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: gamerly_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_gamerly
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: proyecto@gamerly.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data: