server:
  port: ${SPRINGBOOT_PORT}
  error:
    whitelabel:
      enabled: false
    include-message: always
  servlet:
    encoding:
      charset: UTF-8
      force: true


spring:
  application:
    name: project-gamerly
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  secret-key: ${SECRET_KEY}
  access-token-minutes: 300


logging:
  level:
    root: INFO
