server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  application:
    name: project-gamerly
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/gamerly
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
