server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  application:
    name: project-gamerly
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/gamerly
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  secret-key: fc11a8a903105382311a8c17a6595dbc3618b2c0d201c92bf56c7bbf1c4f55cb
  access-token-minutes: 300


logging:
  level:
    root: INFO
