server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  application:
    name: project-gamerly

  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/gamerly
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
